### ISSUE TITLE
change Alejandro Pascual to Alejandro Rodriguez Pascual

### ISSUE THREAD

**Issue by wes-chen** [TritonSE/tritonse.github.io#12]
on tse.ucsd.edu/about

From EOY Feedback form: "Kind of a nitpick that isn't really your fault, but: I noticed that you got my name wrong in All-Hands and the website. This isn't your fault because everyone makes the same mistake, so it's no big deal, but I'd appreciate if you fixed it. Let me explain: my full name is Alejandro Rodriguez Pascual. I usually go by Alex instead of Alejandro because it's shorter and easier to pronounce in English. I don't have a middle name, and my last name is "Rodriguez Pascual", both words! Because of this, everyone seems to think that my middle name is Rodriguez and my last name is Pascual, which isn't the case. Again, kind of a minor thing but I hope it gets fixed for the future. P.S.: if you can't  put Rodriguez Pascual as my last name anywhere for any reason, leaving it as Rodriguez would be fine. Just not Pascual, because then things get really confusing..."

**Comment by dmhacker** [comment]
Did not realize that distinction. It's been fixed on the website; using his full last name now.
