### ISSUE TITLE
Favicon reverted back to default (Gatsby icon)

### ISSUE THREAD

**Issue by wes-chen** [TritonSE/tritonse.github.io#14]
visiting tse.ucsd.edu and tritonse.github.io

![image](https://user-images.githubusercontent.com/35469114/87842600-641a0b00-c862-11ea-979c-3a526a3ebca1.png)

Not sure about root cause...

**Comment by reyna-abhyankar** [comment]
+1 seeing it on my side too

**Comment by dmhacker** [comment]
Resolved.
