### ISSUE TITLE
Subtitle for CCH Community Markets ends in p...

### ISSUE THREAD

**Issue by wes-chen** [TritonSE/tritonse.github.io#9]
http://tse.ucsd.edu/project/cch-website

"We are working with the Center for Community Health to create an online market assessment tool to determine how healthy a market is. The goal is to make their current process more efficient. This allows markets to get accurate information regarding p..."

This sentence does not end?

**Comment by dmhacker** [comment]
I add the ellipses at the end when the subtitles become too long in the cards. This prevents long subtitles from overextending and pushing out other project cards. I've shortened the description to account for this.
